version: '3'

services:
  nova_web:
    image: webdevops/apache:alpine
    container_name: 'nova_web'
    hostname: 'nova_web'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_PHP_SOCKET: nova_php:9000
      LOG_STDOUT: /app/docker/storage/logs/web.access.log
      LOG_STDERR: /app/docker/storage/logs/web.errors.log
    networks:
      default:
        ipv4_address: 192.168.230.101
    volumes:
      - ./:/app:rw,cached
    ports:
      - ${DOCKER_BRIDGE}:80:80
      - ${DOCKER_BRIDGE}:443:443
    working_dir: /app
    depends_on:
      - nova_php
    restart: always

  nova_php:
    build:
      context: docker/dev/php
#      dockerfile: docker/dev/php/Dockerfile
    container_name: 'nova_php'
    hostname: 'nova_php'
    networks:
      default:
        ipv4_address: 192.168.230.110
    volumes:
      - ./:/app:rw,cached
      - ./docker/dev/php/.bashrc:/root/.bashrc
      - ./docker/dev/php/.bash_aliases:/root/.bash_aliases
    working_dir: /app
    environment:
      TERM: xterm-256color
      COMPOSER_ALLOW_SUPERUSER: 1
      XDEBUG_CONFIG: "remote_host=192.168.230.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - ${DOCKER_BRIDGE}:6001:6001
    restart: always
    depends_on:
      - nova_db
    entrypoint: ["/bin/bash", "/usr/bin/php_init.sh"]

  nova_db:
    image: mysql:5.7.28
    container_name: 'nova_db'
    hostname: 'nova_db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    networks:
      default:
        ipv4_address: 192.168.230.120
    volumes:
      - ./docker/storage/db/mysql:/var/lib/mysql


  nova_node:
    image: node:8-slim
    container_name: 'nova_node'
    hostname: 'nova_node'
    working_dir: /app
    volumes:
      - ./:/app:rw,cached
    tty: true
    restart: always

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.230.0/24
